baseURL = "//ziglang.org/"
languageCode = "en-us"
title = "Zig Programming Language"
theme = "ziglang-original"
disableKinds = ["taxonomy", "term"]
timeout = 1000000

[params]
disable_zig_rendering = false
zig_code_basepath = "assets/zig-code/"
downloads_release_order = [
  "master",
  "0.7.1",
  "0.7.0",
  "0.6.0",
  "0.5.0",
  "0.4.0",
  "0.3.0",
  "0.2.0",
  "0.1.1",
]
downloads_arch_order = [
  "src",
  "bootstrap",
  "x86_64-linux",
  "i386-linux",
  "riscv64-linux",
  "aarch64-linux",
  "armv7a-linux",
  "armv6kz-linux",
  "x86_64-macos",
  "x86_64-windows",
  "i386-windows",
  "x86_64-freebsd"
]

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

DefaultContentLanguage = "en"
[languages]
  [languages.en]
    weight = 1
  [languages.it]
    weight = 2
  [languages.pt]
    weight = 2
  [languages.zh]
    weight = 2
